language: cpp

notifications:
    email:
        on_success: change
        on_failure: always

matrix:
    include:
        - os: linux
          compiler: clang

        - os: osx
          compiler: clang

before_install:
    - chmod +x tests/run_tests.sh

before_script:
    - clang --version
    - tests/build/buildtools-premake/bin/premake.sh --version

script:
    - tests/run_tests.sh
