language: cpp

sudo: false

notifications:
    email:
        on_success: change
        on_failure: always

matrix:
    include:
        - os: linux
          compiler: clang
          addons:
            apt:
                sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7' ]
                packages: [ 'libc6-2.16' ]

        - os: osx
          compiler: clang

before_install:
    - chmod +x tests/build/buildtools-premake/bin/linux/premake5
    - chmod +x tests/run_tests.sh

before_script:
    - cd /lib/x86_64-linux-gnu/; ls -l libc*.so*
    - tests/build/buildtools-premake/bin/premake.sh --version

script:
    - tests/run_tests.sh
