language: cpp

notifications:
    email:
        on_success: change
        on_failure: always

os:
    - linux
    - osx

compiler:
    - clang

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7' ]
    packages: [ 'clang-3.7' ]

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CXX=clang++-3.7; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $CXX --version; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then clang --version; fi
    - tests/build/buildtools-premake/bin/build.sh
    - tests/build/buildtools-premake/bin/premake.sh --version

script:
    - tests/run_tests.sh
