language: cpp

notifications:
    email:
        on_success: change
        on_failure: always

matrix:
    include:
        - os: linux
          compiler: clang
          env: INSTALL_CXX=clang++-3.7
          addons:
            apt:
                sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7' ]
                packages: [ 'clang-3.7' ]

        - os: osx
          compiler: clang

before_install:
    - chmod +x tests/run_tests.sh

before_script:
    - if [ -n "${INSTALL_CXX}" ]; then
        CXX=${INSTALL_CXX};
      fi
    - clang --version
    - tests/build/buildtools-premake/bin/build.sh
    - tests/build/buildtools-premake/bin/premake.sh --version

script:
    - tests/run_tests.sh
