language: cpp

sudo: false

notifications:
    email:
        on_success: change
        on_failure: always

os:
    - linux
    - osx

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libc6
    - chmod +x tests/build/buildtools-premake/bin/linux/premake5
    - chmod +x tests/run_tests.sh

before_script:
    - tests/build/buildtools-premake/bin/premake.sh --version

script:
    - tests/run_tests.sh
